import torch
import argparse
import os

from src.data.dataset import get_dataloader
from src.models.fno import FNO2d
from src.models.periodic_unet import PeriodicUNet
from src.training.data_driven_trainer import DataDrivenTrainer

def train(args):
    # Setup Device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Load Data
    # Assuming simulation_results_diverse.h5 is generated by generate_dataset.py
    data_path = args.data_path
    if not os.path.exists(data_path):
        print(f"Dataset not found at {data_path}. Please run generate_dataset.py first.")
        return

    print("Loading dataset...")
    # seq_len=10 for autoregressive rollout
    dataloader = get_dataloader(data_path, batch_size=args.batch_size, seq_len=args.seq_len, shuffle=True)

    # Instantiate Model
    print(f"Initializing {args.model} model...")
    if args.model == "fno":
        # in_channels: 4 (P(t-1), P(t-2), S(t-1), M)
        model = FNO2d(modes=12, width=32, in_channels=4, out_channels=1)
    elif args.model == "unet":
        # in_channels: 4 (P(t-1), P(t-2), S(t-1), M)
        model = PeriodicUNet(n_channels=4, n_classes=1)
    else:
        raise ValueError(f"Unknown model: {args.model}")

    # Initialize Trainer
    trainer = DataDrivenTrainer(model, lr=args.lr)

    # Train
    print("Starting training loop...")
    trainer.train_epochs(
        train_loader=dataloader, 
        val_loader=None, # You can split dataloader into train/val if you have a larger dataset
        epochs=args.epochs, 
        initial_teacher_forcing=0.5
    )

    # Save Model
    save_dir = "src/models/saved"
    os.makedirs(save_dir, exist_ok=True)
    save_path = os.path.join(save_dir, f"{args.model}_best.pth")
    torch.save(model.state_dict(), save_path)
    print(f"Training completed. Model saved to {save_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Data-Driven Wave Models")
    parser.add_argument('--model', type=str, default='fno', choices=['fno', 'unet'], help='Model architecture to use.')
    parser.add_argument('--data_path', type=str, default='src/data/simulation_results_diverse.h5', help='Path to HDF5 dataset.')
    parser.add_argument('--batch_size', type=int, default=8, help='Batch size for training.')
    parser.add_argument('--seq_len', type=int, default=10, help='Autoregressive rollout sequence length.')
    parser.add_argument('--epochs', type=int, default=20, help='Number of epochs to train.')
    parser.add_argument('--lr', type=float, default=1e-4, help='Learning rate.')
    
    args = parser.parse_args()
    train(args)
